version: "3"

services: 
    web:
        container_name: healthcare-api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app

    nutrition:
        container_name: nutritional-api
        restart: always
        build:
            context: nutritional-health-api/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
            
    mongo:
        container_name: mongodatabase
        image: mongo:4.4
        ports: 
            - "27018:27017" 
        logging:
            driver: none
